backend:
  name: git-gateway
  branch: main

media_folder: "images/performers"
public_folder: "/images/performers"

collections:
  - name: "performers"
    label: "Performers"
    folder: "content/performers"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Main Photo", name: "photo", widget: "image"}
      - {label: "Additional Photos", name: "photos", widget: "list", field: {label: "Photo", name: "photo", widget: "image"}, required: false}
      - {label: "Specialties", name: "specialties", widget: "string"}
      - {label: "Bio", name: "bio", widget: "text", required: false}
      
  - name: "settings"
    label: "Site Settings"
    files:
      - file: "content/homepage.md"
        label: "Homepage Content"
        name: "homepage"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Main Text", name: "main_text", widget: "markdown"}
